# SPDX-License-Identifier: MPL-2.0-or-later
name: OSSF Scorecard
on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * 0'

permissions: read-all

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@05bb7c663f6ec9bd8484da0a5b5a77d423e3f88c # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v3
        with:
          sarif_file: results.sarif
